theme: jekyll-theme-minimal
title: CodeX Academy Badge Competencies
description: Online home of CodeX Academy's library of technical competencies.
logo: https://www.codex.academy/img/logo/horizontal_logo.png
show_downloads: false
